import Stripe from "stripe";

// After a PaymentIntent succeeds, fetch Stripe's real hosted receipt URL from the
// charge. This is the authoritative receipt document, generated by Stripe, that
// we link to in-app and in the confirmation email.
export async function GET(req: Request) {
  const id = new URL(req.url).searchParams.get("pi");
  const key = process.env.STRIPE_SECRET_KEY;
  if (!id || !key) return Response.json({ receiptUrl: null });
  try {
    const stripe = new Stripe(key);
    const pi = await stripe.paymentIntents.retrieve(id, { expand: ["latest_charge"] });
    const charge = pi.latest_charge as Stripe.Charge | null;
    return Response.json({
      receiptUrl: charge?.receipt_url ?? null,
      status: pi.status,
      paid: pi.status === "succeeded",
    });
  } catch (e) {
    return Response.json({ receiptUrl: null, error: String(e) });
  }
}
